name: Test linux job

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract package.json content
        id: set_var
        run: |
          content=`cat ./package.json` # Adjust the path to your actual package.json file
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"

      - name: Log extracted version
        run: |
          echo "Extracted version: ${{ fromJson(steps.set_var.outputs.packageJson).version }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ozkar-server:${{ fromJson(steps.set_var.outputs.packageJson).version }}
