name: Build Dockerfile 

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from package.json and set as environment variable
        run: |
          version=$(jq -r '.version' ./package.json)
          echo "version=$version" >> $GITHUB_ENV

      - name: Log extracted version
        run: echo "Extracted version: ${{ env.version }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ozkar-server:${{ env.version }}
