query ProveQuery($proofRequests: CreateProofInput!) {
  proveQuery(proofRequests: $proofRequests)
}


query GetUserWorkflows($publicKey: String!,$status: String!, $resourceIds: [String]!) {
  getUserWorkflows(
    publicKey: $publicKey
    status: $status
    resourceIds: $resourceIds
    #
  )
}
query GetProofsResults($workflowIds: [String]!) {
  getProofsResults(
    signature: ""
    workflowIds: $workflowIds
  )
}
