query ProveQuery($proofRequests: CreateProofInput!) {
  proveQuery(proofRequests: $proofRequests)
}

query GetUserWorkflows {
  getUserWorkflows(
    publicKey: "yourPublicKeyHere"
    status: "Running"
    resourceId: "resourceID"
  )
}
