query ProveQuery($proofRequests: CreateProofInput!) {
  proveQuery(proofRequests: $proofRequests)
}

# Write your query or mutation here
query GetUserWorkflows($publicKey: String!,$status: String!, $resourceId: String!) {
  getUserWorkflows(
    publicKey: $publicKey
    status: $status
    resourceId: $resourceId
    #
  )
}

query GetProofResult($workflowId: String!) {
  getProofResult(
    signature: ""
    workflowId: $workflowId
  )
}
